# Generated by Django 5.2.8 on 2025-11-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
