# Generated by Django 5.2.8 on 2025-11-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_smartphone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='product_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
