# Generated by Django 5.2.8 on 2025-11-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_smartphone_product_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='product_key',
            new_name='product_code',
        ),
    ]
