# Generated by Django 5.2.8 on 2025-11-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_rename_product_key_smartphone_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='price',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
