# Generated by Django 5.2.8 on 2025-11-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_smartphone_discounted_price_smartphone_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='reviews',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
