# Generated by Django 5.2.8 on 2025-11-18 22:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_smartphone_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='image_paths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
