# Generated by Django 5.2.8 on 2025-11-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_smartphone_image_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='characteristics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
