# Generated by Django 5.2.8 on 2025-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0008_smartphone_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='dealer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
