# Generated by Django 5.2.8 on 2025-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0009_smartphone_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='internal_memory',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
