# Generated by Django 5.2.8 on 2025-11-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0010_smartphone_internal_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='screen_diagonal',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='series',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='internal_memory',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
